# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-18 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productattribute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttribute',
            new_name='ProductAttribute1',
        ),
    ]
