# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-18 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20161218_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute1',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patt', to='shop.Product'),
        ),
    ]
