# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-18 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20161218_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttribute1',
            new_name='ProductAttribute',
        ),
    ]
