# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-18 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20161218_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={},
        ),
    ]
